version: '3.8'

services:
  dev:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000" # Port for Vite dev server
    command: yarn dev
    environment:
      - NODE_ENV=development
    networks:
      - mynetwork

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Use port 8080 to avoid conflict with port 80
    environment:
      - NODE_ENV=production
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
